name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: yarn
      - run: yarn build
      - run: ls -al
      - run: cp .yarnrc.yml ./packages/openapi-to-graphql
      - run: cp .yarnrc.yml ./packages/openapi-to-graphql-cli
        run: cp -R .yarn ./packages/openapi-to-graphql
      - run: cp -R .yarnrc.yml ./packages/openapi-to-graphql-cli
      - run: cd ./packages/openapi-to-graphql && yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: cd ./packages/openapi-to-graphql-cli && yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
